apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: service-my-kube-test-app
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 5173
      targetPort: 5173
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: kube-test-app-yaml
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer
