apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-food-orders
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mydata/orders.txt
    type: FileOrCreate
